chore: audit fix
- After the node version bump from 12.x to 18.x we got [following error](https://github.com/rwjblue/ember-cli-content-security-policy/actions/runs/8834593920/job/24256659316?pr=366):

```
⠏ building... [Concat: Test Support JS]node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/michal/ember/ember-cli-content-security-policy/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/michal/ember/ember-cli-content-security-policy/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/michal/ember/ember-cli-content-security-policy/node_modules/webpack/lib/NormalModule.js:460:10
    at /Users/michal/ember/ember-cli-content-security-policy/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/michal/ember/ember-cli-content-security-policy/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/michal/ember/ember-cli-content-security-policy/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/michal/ember/ember-cli-content-security-policy/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/michal/ember/ember-cli-content-security-policy/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16) {
  opensslErrorStack: [ error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'

```
This seems to be [answered here](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported) and the recommended course of action:
quote>
```
npm_config_yes=true npx yarn-audit-fix
```
quote>
Which is the outcome of this commit